//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStudent2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class estudentEntities4 : DbContext
    {
        public estudentEntities4()
            : base("name=estudentEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<izpitnirok> izpitnirok { get; set; }
        public DbSet<ocena> ocena { get; set; }
        public DbSet<predmet> predmet { get; set; }
        public DbSet<studentpredmet> studentpredmet { get; set; }
        public DbSet<uporabnik> uporabnik { get; set; }
        public DbSet<vloga> vloga { get; set; }
    }
}
