//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStudent2
{
    using System;
    using System.Collections.Generic;
    
    public partial class predmet
    {
        public predmet()
        {
            this.izpitnirok = new HashSet<izpitnirok>();
            this.ocena = new HashSet<ocena>();
            this.studentpredmet = new HashSet<studentpredmet>();
        }
    
        public int idPredmet { get; set; }
        public string imePredmeta { get; set; }
        public int idIzvajalca { get; set; }
        public int stKreditnih { get; set; }
    
        public virtual ICollection<izpitnirok> izpitnirok { get; set; }
        public virtual ICollection<ocena> ocena { get; set; }
        public virtual ICollection<studentpredmet> studentpredmet { get; set; }
        public virtual uporabnik uporabnik { get; set; }
    }
}
