//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStudentMVC5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class estudentEntities : DbContext
    {
        public estudentEntities()
            : base("name=estudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<izpitnirok> izpitnirok { get; set; }
        public virtual DbSet<ocena> ocena { get; set; }
        public virtual DbSet<predmet> predmet { get; set; }
        public virtual DbSet<studentpredmet> studentpredmet { get; set; }
        public virtual DbSet<uporabnik> uporabnik { get; set; }
        public virtual DbSet<vloga> vloga { get; set; }
    }
}
