//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStudentMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class izpitnirok
    {
        public izpitnirok()
        {
            this.ocena = new HashSet<ocena>();
        }
    
        public int idIzpitniRok { get; set; }
        public int idPredmeta { get; set; }
        public int stRoka { get; set; }
        public System.DateTime datum { get; set; }
        public string prostor { get; set; }
        public string komentar { get; set; }
        public Nullable<bool> zakljucen { get; set; }
    
        public virtual predmet predmet { get; set; }
        public virtual ICollection<ocena> ocena { get; set; }
    }
}
