//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStudentMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentpredmet
    {
        public int idStudentPredmet { get; set; }
        public int idStudenta { get; set; }
        public int idPredmeta { get; set; }
        public Nullable<bool> opravljen { get; set; }
    
        public virtual predmet predmet { get; set; }
        public virtual uporabnik uporabnik { get; set; }
    }
}
