//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStudentMVC5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Newtonsoft.Json;
    
    public partial class uporabnik
    {
        public uporabnik()
        {
            this.ocena = new HashSet<ocena>();
            this.predmet = new HashSet<predmet>();
            this.studentpredmet = new HashSet<studentpredmet>();
        }

        [Required]
        public int idUporabnik { get; set; }

        public Nullable<int> vpisnaStevilka { get; set; }

        [Required]
        [RegularExpression(@"^[A-z]*$", ErrorMessage = "Neveljavno ime.")]
        public string ime { get; set; }

        [Required]
        [RegularExpression(@"^[A-z]*$", ErrorMessage = "Neveljaven priimek.")]
        public string priimek { get; set; }

        [RegularExpression(@"^[\w\d-\.]+@([\w\d-]+\.)+[\w-]{2,4}$", ErrorMessage = "Neveljaven elektronski naslov.")]
        public string email { get; set; }

        public string geslo { get; set; }

        [Required]
        public string mobi { get; set; }

        [Required]
        [RegularExpression(@"^[MZ]*$", ErrorMessage = "Neveljaven spol.")]
        public string spol { get; set; }

        [RegularExpression(@"^[123]{1}$", ErrorMessage = "Neveljaven letnik studija.")]
        public Nullable<int> letnikStudija { get; set; }

        public System.DateTime datumRegistracije { get; set; }

        public System.DateTime zadnjiDostop { get; set; }

        public int idVloge { get; set; }

        [JsonIgnore]
        public virtual ICollection<ocena> ocena { get; set; }

        [JsonIgnore]
        public virtual ICollection<predmet> predmet { get; set; }

        [JsonIgnore]
        public virtual ICollection<studentpredmet> studentpredmet { get; set; }

        [JsonIgnore]
        public virtual vloga vloga { get; set; }
    }
}
