//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStudentMVC5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class vloga
    {
        public vloga()
        {
            this.uporabnik = new HashSet<uporabnik>();
        }

        [Required]
        public int idVloga { get; set; }

        [Required]
        public string nazivVloge { get; set; }
    
        public virtual ICollection<uporabnik> uporabnik { get; set; }
    }
}
